[phases.setup]
nixPkgs = ["glib", "nss", "nspr", "dbus", "atk", "cups", "libdrm", "xcb", "xkbcommon", "pango", "cairo", "alsa-lib"]

[phases.install]
cmds = ["python -m playwright install chromium"]

[start]
cmd = "gunicorn api_server:app --bind 0.0.0.0:$PORT"
