[phases.setup]
nixPkgs = ["python311", "chromium"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "playwright install chromium",
    "playwright install-deps"
]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "./start.sh"
