[phases.setup]
nixPkgs = ["python311", "chromium", "curl"]

[phases.install]
cmds = [
    "curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py",
    "python get-pip.py --force-reinstall",
    "python -m pip install -r requirements.txt",
    "python -m playwright install chromium",
    "python -m playwright install-deps"
]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "./start.sh"
