[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
    "python -m ensurepip --user",
    "python -m pip install --user -r requirements.txt",
    "python -m playwright install chromium",
    "python -m playwright install-deps"
]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "./start.sh"
