[phases.setup]
nixPkgs = ["glib", "nss", "nspr", "dbus", "atk", "cups", "pango", "cairo"]
cmds = ["pip install playwright", "playwright install chromium"]

[start]
cmd = "gunicorn api_server:app --bind 0.0.0.0:$PORT"
