[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "chromium"]

[phases.install]
cmds = [
    "python -m pip install -r requirements.txt",
    "python -m playwright install chromium",
    "python -m playwright install-deps"
]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "./start.sh"
