[build]
builder = "nixpacks"

[deploy]
startCommand = "python -m playwright install chromium && gunicorn api_server:app --bind 0.0.0.0:$PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
